// Auto-generated by register_ops_tflite(). Do not edit.
#include "register_operators.h"
#include "tensorflow/lite/kernels/op_macros.h"

namespace tinyfm {

TfLiteStatus RegisterGeneratedOps(GeneratedOpResolver& op_resolver) {
  // BuiltinOperator_CONV_2D (3)
  TF_LITE_ENSURE_STATUS(op_resolver.AddConv2D());
  // BuiltinOperator_DEQUANTIZE (6)
  TF_LITE_ENSURE_STATUS(op_resolver.AddDequantize());
  // BuiltinOperator_FULLY_CONNECTED (9)
  TF_LITE_ENSURE_STATUS(op_resolver.AddFullyConnected());
  // BuiltinOperator_RESHAPE (22)
  TF_LITE_ENSURE_STATUS(op_resolver.AddReshape());
  // BuiltinOperator_SOFTMAX (25)
  TF_LITE_ENSURE_STATUS(op_resolver.AddSoftmax());
  // BuiltinOperator_STRIDED_SLICE (45)
  TF_LITE_ENSURE_STATUS(op_resolver.AddStridedSlice());
  // BuiltinOperator_SHAPE (77)
  TF_LITE_ENSURE_STATUS(op_resolver.AddShape());
  // BuiltinOperator_PACK (83)
  TF_LITE_ENSURE_STATUS(op_resolver.AddPack());
  return kTfLiteOk;
}

}  // namespace tinyfm
