// Auto-generated by register_ops_tflite(). Do not edit.
#pragma once

#include "tensorflow/lite/core/c/common.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"

namespace tinyfm {
constexpr int kResolverOpCount = 8;
using GeneratedOpResolver = tflite::MicroMutableOpResolver<kResolverOpCount>;

TfLiteStatus RegisterGeneratedOps(GeneratedOpResolver& op_resolver);

}  // namespace tinyfm
